spring:
    application:
        name: ttsx-gateway
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    redis:
        host: 192.168.88.128
        port: 6379
        database: 2
        password: 123456
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
                username: nacos
                password: nacos
                namespace: ttsx-prod
        gateway:
            globalcors: #全局跨域处理
                cors-configurations:
                    '[/**]':
                        allowedOriginPatterns: "*"
                        allowedHeaders: "*"
                        exposedHeaders:
                            - Content-Type
                            - Authorization
                        allowedMethods: "*"
                        #要注意的是，当 Access-Control-Allow-Credentials 的值为 true 时，Access-Control-Allow-Origin 的值只能是请求的 Origin，不能是 *
                        #            allowedOrigins: "*"
                        #            Access-Control-Allow-Origin: "*"
                        allowCredentials: true   #并且允许携带身份凭证
            #            allowCredentials: true   #并且允许携带身份凭证
            routes:
                -   id: ttsx-inedx
                    uri: lb://ttsx-index
                    predicates: #路由断言
                        - Path=/ttsxindex/**     #http://localhost:10010/resindex/index.html
                    filters:
                        - RewritePath=/ttsxindex/(?<segment>.*), /$\{segment}  #将 resindex/index.html  -->  index.html
                -   id: ttsx-order-addr
                    uri: lb://ttsx-order
                    predicates:
                        - Path=/addr/**

                -   id: ttsx-user
                    uri: lb://ttsx-user
                    predicates:
                        - Path=/user/**

                -   id: ttsx-foods
                    uri: lb://ttsx-foods
                    predicates:
                        - Path=/goods/**
                    filters:
                #           - RewritePath=/foods/(?<segment>.*), /$\{segment}
                -   id: ttsx-order
                    uri: lb://ttsx-order
                    predicates:
                        - Path=/order/**

                -   id: ttsx-order-cart
                    uri: lb://ttsx-order
                    predicates:
                        - Path=/cart/**
                    filters:
                #            - RewritePath=/foods/(?<segment>.*), /$\{segment}

                -   id: ttsx-backgroud
                    uri: lb://ttsx-backgroud
                    predicates:
                        - Path=/backgroud/**
                -   id: ttsx-FlashKilling
                    uri: lb://ttsx-FlashKilling
                    predicates:
                        - Path=/fk/**

                -   id: websocket-service
                    uri: lb://websocket-service
                    predicates:
                        - Path=/ws/**
                -   id: ttsx-pay
                    uri: lb://ttsx-pay
                    predicates:
                        - Path=/alipay/**

server:
    port: 20001  #网关端口

management:
    endpoints:
        web:
            exposure:
                include: "*"    # 暴露gateway端点，* 是暴露全部端点
    endpoint:
        gateway:
            enabled: true # default value